name: Maven Build and Test
on: [push]
jobs:
  Maven-Build-Test-Action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Install dependencies
        run: mvn clean install
      - name: Run Maven tests
        run: mvn test

